# config-repo/values-dev.yaml
replicaCount: 4
image:
  repository: nginx
  tag: 1.25.3 # Dev might use a slightly older or specific version
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
