# config-repo/values-prod.yaml
replicaCount: 3
image:
  repository: nginx
  tag: 1.26.1 # Prod uses the latest stable
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: nginx
  hosts:
    - host: my-nginx.prod.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
